### ISSUE TITLE
Len's-Gemology - ore crystals aren't growing no matter the depths.

### ISSUE THREAD

**Issue by VladislavLiubasiuk** [V2LenKagamine/LensVintageModding#1]
Essentially the title. After more than half the winter has passed (12 days per months), not a single crystal has grown from the starting stage. They are located right on the mantle.

**Comment by V2LenKagamine** [comment]
Hmm, odd, will check into this.

**Comment by VladislavLiubasiuk** [comment]
> Hmm, odd, will check into this.

If you need additional info, please let me know. While I use plenty of mods, I don't think any of them should affect gems. (the only suspcision I have, is having bigger default depths, and Geology Additions ,somehow affect them?)

**Comment by VladislavLiubasiuk** [comment]
Any updates?

**Comment by V2LenKagamine** [comment]
Been really busy, sadly not. Will close when I get to it

**Comment by VladislavLiubasiuk** [comment]
> Been really busy, sadly not. Will close when I get to it

After some testing in the creative mode (with absolute prospecting disabled, although I doubt it is related), they do seem to grow up, but not within 3 days (surface level, super flat), but kinda randomly (I tried add 30/30000 hours to the date, and they would occasionally grow up to the next size, after multiple time skips.

Maybe the growth mechanic is bugged/scuffed?

**Comment by V2LenKagamine** [comment]
> > Been really busy, sadly not. Will close when I get to it
> 
> After some testing in the creative mode (with absolute prospecting disabled, although I doubt it is related), they do seem to grow up, but not within 3 days (surface level, super flat), but kinda randomly (I tried add 30/30000 hours to the date, and they would occasionally grow up to the next size, after multiple time skips.
> 
> Maybe the growth mechanic is bugged/scuffed?

The issue has been resolved as of 1.0.1, and was caused by an errant `return` left in the growth function!
